# Generated by Django 3.2.12 on 2022-04-23 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email1', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=24)),
                ('vuln_type', models.CharField(max_length=24)),
                ('vuln_title', models.CharField(max_length=24)),
                ('vuln_description', models.TextField(max_length=200)),
                ('vuln_attachments', models.FileField(upload_to='')),
                ('tc_consent', models.BooleanField()),
                ('date_sumbmitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
