# Generated by Django 3.2.12 on 2022-04-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='author_email1',
            new_name='author_email',
        ),
    ]
