# Generated by Django 3.2.12 on 2022-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_author_email1_submission_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_sumbmitted',
            field=models.DateTimeField(),
        ),
    ]
