# Generated by Django 3.2.12 on 2022-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_submission_date_sumbmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_sumbmitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
