# Generated by Django 3.2.12 on 2022-04-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_submission_date_sumbmitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='tc_consent',
            new_name='is_approved',
        ),
    ]
