# Generated by Django 3.2.12 on 2022-04-23 20:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_tc_consent_submission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_sumbmitted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 23, 20, 42, 0, 534094, tzinfo=utc)),
        ),
    ]
