# Generated by Django 3.2.12 on 2022-04-23 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_submission_date_sumbmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_sumbmitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
