# Generated by Django 3.2.12 on 2022-04-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_submission_date_sumbmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
