# Generated by Django 3.2.12 on 2022-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_date_sumbmitted_submission_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_approved',
            field=models.BooleanField(blank=True),
        ),
    ]
