# Generated by Django 3.2.12 on 2022-04-23 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_submission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
