# Generated by Django 3.2.12 on 2022-04-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_submission_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=30)),
                ('tutorial_author', models.CharField(max_length=24)),
                ('tutorial_category', models.CharField(choices=[('cstools', 'Cyber Sec Tools'), ('networking', 'Networking'), ('misc', 'Misc')], max_length=200)),
                ('tutorial_link', models.URLField()),
            ],
        ),
    ]
