# Generated by Django 3.2.12 on 2022-05-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220502_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_link',
            new_name='tutorial_video_link',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_description_text',
            field=models.TextField(default=None),
        ),
    ]
